# OpenTelemetry Collector (logging demo)
# Receives OTLP traces/metrics/logs and prints them to stdout.
# This is the fastest way to show end-to-end tracing without AWS wiring.

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
