use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Correlation identifiers for KMS proxy requests.
///
/// `request_id` is generated by the caller (enclave) and must be echoed by the host.
/// `trace_id` is optional and can be used to stitch together multi-hop traces.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct KmsProxyRequestEnvelope {
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    pub request: KmsRequest,
}

/// Correlated response envelope for KMS proxy requests.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct KmsProxyResponseEnvelope {
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    /// AWS-side request id (when available) for debugging with AWS support / CloudTrail.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_request_id: Option<String>,
    pub response: KmsResponse,
}

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum KmsProxyErrorCode {
    Timeout,
    InvalidRequest,
    UpstreamAccessDenied,
    UpstreamThrottled,
    UpstreamUnavailable,
    Internal,
}

/// KMS Request types (matching Host definition)
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(tag = "op", content = "payload")]
pub enum KmsRequest {
    Decrypt {
         ciphertext_blob: Vec<u8>,
         key_id: Option<String>,
         encryption_context: Option<HashMap<String, String>>,
         grant_tokens: Option<Vec<String>>,
         recipient: Option<Vec<u8>>, // Attestation document
    },
    GenerateDataKey {
        key_id: String,
        key_spec: String,
    },
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum KmsResponse {
    Decrypt {
        /// If Recipient was provided in request, this contains the payload encrypted to the recipient key.
        ciphertext_for_recipient: Option<Vec<u8>>,
        /// If Recipient was NOT provided, this contains plaintext (NOT SAFE for Enclaves).
        plaintext: Option<Vec<u8>>,
        key_id: Option<String>,
    },
    GenerateDataKey {
        ciphertext_blob: Vec<u8>,
        plaintext: Vec<u8>,
        key_id: String,
    },
    Error {
        code: KmsProxyErrorCode,
        /// Redacted, caller-safe error message.
        message: String,
    },
}
